# Streamlit Secrets Configuration
# Place this file in .streamlit/secrets.toml

# API Configuration
API_BASE_URL = "http://localhost:8000"

# If deploying to production, update the URL:
# API_BASE_URL = "https://your-api-domain.com"
